export const mockBusinesses = [
  {
    id: "1",
    name: "Al-Madina Restaurant",
    category: "Restaurants",
    city: "karachi",
    phone: "+92-21-34567890",
    image: "/pakistani-restaurant-interior.webp",
  },
  {
    id: "2",
    name: "City Hospital",
    category: "Healthcare",
    city: "lahore",
    phone: "+92-42-35678901",
    image: "/modern-hospital.webp",
  },
  {
    id: "3",
    name: "Tech Solutions Hub",
    category: "Technology",
    city: "islamabad",
    phone: "+92-51-23456789",
    image: "/modern-tech-office.webp",
  },
  {
    id: "4",
    name: "Green Valley School",
    category: "Education",
    city: "rawalpindi",
    phone: "+92-51-34567890",
    image: "/school-building-with-playground.webp",
  },
  {
    id: "5",
    name: "Auto Care Center",
    category: "Automotive",
    city: "faisalabad",
    phone: "+92-41-23456789",
    image: "/car-repair-garage.webp",
  },
  {
    id: "6",
    name: "Fashion Plaza",
    category: "Retail",
    city: "karachi",
    phone: "+92-21-45678901",
    image: "/clothing-store-interior.webp",
  },
  {
    id: "7",
    name: "Beauty Lounge",
    category: "Beauty & Spa",
    city: "lahore",
    phone: "+92-42-45678901",
    image: "/modern-beauty-salon.webp",
  },
  {
    id: "8",
    name: "Prime Properties",
    category: "Real Estate",
    city: "islamabad",
    phone: "+92-51-56789012",
    image: "/real-estate-office.webp",
  },
  {
    id: "9",
    name: "Legal Associates",
    category: "Legal Services",
    city: "karachi",
    phone: "+92-21-67890123",
    image: "/law-office-interior.webp",
  },
  {
    id: "10",
    name: "Build Right Construction",
    category: "Construction",
    city: "rawalpindi",
    phone: "+92-51-78901234",
    image: "/construction-company-office.webp",
  },
  {
    id: "11",
    name: "Travel World",
    category: "Travel & Tourism",
    city: "lahore",
    phone: "+92-42-78901234",
    image: "/travel-agency-office.webp",
  },
  {
    id: "12",
    name: "Financial Advisors",
    category: "Financial Services",
    city: "islamabad",
    phone: "+92-51-89012345",
    image: "/financial-advisor-office.webp",
  },
]

export const cities = [
  { name: "Karachi", slug: "karachi", businesses: 3200 },
  { name: "Lahore", slug: "lahore", businesses: 2800 },
  { name: "Islamabad", slug: "islamabad", businesses: 1900 },
  { name: "Rawalpindi", slug: "rawalpindi", businesses: 1200 },
  { name: "Faisalabad", slug: "faisalabad", businesses: 980 },
  { name: "Multan", slug: "multan", businesses: 750 },
  { name: "Hyderabad", slug: "hyderabad", businesses: 700 },
  { name: "Peshawar", slug: "peshawar", businesses: 650 },
  { name: "Quetta", slug: "quetta", businesses: 420 },
  { name: "Sialkot", slug: "sialkot", businesses: 380 },
  { name: "Gujranwala", slug: "gujranwala", businesses: 320 },
  { name: "Bahawalpur", slug: "bahawalpur", businesses: 300 },
  { name: "Sargodha", slug: "sargodha", businesses: 290 },
  { name: "Sukkur", slug: "sukkur", businesses: 280 },
  { name: "Larkana", slug: "larkana", businesses: 260 },
  { name: "Sheikhupura", slug: "sheikhupura", businesses: 250 },
  { name: "Gujrat", slug: "gujrat", businesses: 230 },
  { name: "Jhelum", slug: "jhelum", businesses: 220 },
  { name: "Kasur", slug: "kasur", businesses: 210 },
  { name: "Okara", slug: "okara", businesses: 200 },
  { name: "Rahim Yar Khan", slug: "rahim-yar-khan", businesses: 200 },
  { name: "Sahiwal", slug: "sahiwal", businesses: 190 },
  { name: "Dera Ghazi Khan", slug: "dera-ghazi-khan", businesses: 180 },
  { name: "Muzaffargarh", slug: "muzaffargarh", businesses: 170 },
  { name: "Khanewal", slug: "khanewal", businesses: 170 },
  { name: "Vehari", slug: "vehari", businesses: 160 },
  { name: "Lodhran", slug: "lodhran", businesses: 150 },
  { name: "Chiniot", slug: "chiniot", businesses: 150 },
  { name: "Toba Tek Singh", slug: "toba-tek-singh", businesses: 150 },
  { name: "Hafizabad", slug: "hafizabad", businesses: 140 },
  { name: "Nankana Sahib", slug: "nankana-sahib", businesses: 140 },
  { name: "Burewala", slug: "burewala", businesses: 130 },
  { name: "Kamoke", slug: "kamoke", businesses: 130 },
  { name: "Wah Cantt", slug: "wah-cantt", businesses: 130 },
  { name: "Taxila", slug: "taxila", businesses: 120 },
  { name: "Chakwal", slug: "chakwal", businesses: 120 },
  { name: "Attock", slug: "attock", businesses: 120 },
  { name: "Mianwali", slug: "mianwali", businesses: 110 },
  { name: "Bhakkar", slug: "bhakkar", businesses: 110 },
  { name: "Khushab", slug: "khushab", businesses: 110 },
  { name: "Jhang", slug: "jhang", businesses: 110 },
  { name: "Sadiqabad", slug: "sadiqabad", businesses: 110 },
  { name: "Gojra", slug: "gojra", businesses: 100 },
  { name: "Muridke", slug: "muridke", businesses: 100 },
  { name: "Jaranwala", slug: "jaranwala", businesses: 100 },
  { name: "Pakpattan", slug: "pakpattan", businesses: 100 },
  { name: "Arifwala", slug: "arifwala", businesses: 100 },
  { name: "Renala Khurd", slug: "renala-khurd", businesses: 90 },
  { name: "Hasilpur", slug: "hasilpur", businesses: 90 },
  { name: "Daska", slug: "daska", businesses: 90 },
  { name: "Narowal", slug: "narowal", businesses: 90 },
  { name: "Mandi Bahauddin", slug: "mandi-bahauddin", businesses: 90 },
  { name: "Kharian", slug: "kharian", businesses: 90 },
  { name: "Sahiwal (Sargodha)", slug: "sahiwal-sgd", businesses: 80 },
  { name: "Haripur", slug: "haripur", businesses: 90 },
  { name: "Abbottabad", slug: "abbottabad", businesses: 150 },
  { name: "Mansehra", slug: "mansehra", businesses: 120 },
  { name: "Swat (Mingora)", slug: "mingora", businesses: 140 },
  { name: "Nowshera", slug: "nowshera", businesses: 110 },
  { name: "Charsadda", slug: "charsadda", businesses: 100 },
  { name: "Mardan", slug: "mardan", businesses: 160 },
  { name: "Kohat", slug: "kohat", businesses: 100 },
  { name: "Bannu", slug: "bannu", businesses: 90 },
  { name: "Dera Ismail Khan", slug: "dera-ismail-khan", businesses: 100 },
  { name: "Hangu", slug: "hangu", businesses: 80 },
  { name: "Karak", slug: "karak", businesses: 80 },
  { name: "Gilgit", slug: "gilgit", businesses: 70 },
  { name: "Skardu", slug: "skardu", businesses: 60 },
  { name: "Hunza", slug: "hunza", businesses: 50 },
  { name: "Muzaffarabad", slug: "muzaffarabad", businesses: 90 },
  { name: "Mirpur (AJK)", slug: "mirpur-ajk", businesses: 80 },
  { name: "Kotli", slug: "kotli", businesses: 80 },
  { name: "Quetta Cantonment", slug: "quetta-cantt", businesses: 50 },
  { name: "Gwadar", slug: "gwadar", businesses: 40 },
  { name: "Turbat", slug: "turbat", businesses: 40 },
  { name: "Khuzdar", slug: "khuzdar", businesses: 50 },
  { name: "Sibi", slug: "sibi", businesses: 40 },
  { name: "Zhob", slug: "zhob", businesses: 40 },
  { name: "Killa Saifullah", slug: "killa-saifullah", businesses: 30 },
  { name: "Loralai", slug: "loralai", businesses: 30 },
  { name: "Panjgur", slug: "panjgur", businesses: 30 },
  { name: "Lasbela", slug: "lasbela", businesses: 30 },
  { name: "Hub", slug: "hub", businesses: 120 },
  { name: "Dadu", slug: "dadu", businesses: 80 },
  { name: "Jamshoro", slug: "jamshoro", businesses: 70 },
  { name: "Thatta", slug: "thatta", businesses: 70 },
  { name: "Badin", slug: "badin", businesses: 70 },
  { name: "Mirpur Khas", slug: "mirpur-khas", businesses: 100 },
  { name: "Umerkot", slug: "umerkot", businesses: 60 },
  { name: "Nawabshah (Shaheed Benazirabad)", slug: "nawabshah", businesses: 110 },
  { name: "Sanghar", slug: "sanghar", businesses: 80 },
  { name: "Hala", slug: "hala", businesses: 50 },
  { name: "Matiari", slug: "matiari", businesses: 40 },
  { name: "Shikarpur", slug: "shikarpur", businesses: 80 },
  { name: "Jacobabad", slug: "jacobabad", businesses: 80 },
  { name: "Ghotki", slug: "ghotki", businesses: 70 },
  { name: "Kandhkot", slug: "kandhkot", businesses: 60 },
  { name: "Kot Addu", slug: "kot-addu", businesses: 70 },
  { name: "Jatoi", slug: "jatoi", businesses: 40 },
  { name: "Hujra Shah Muqeem", slug: "hujra-shah-muqeem", businesses: 30 },
  { name: "Fort Abbas", slug: "fort-abbas", businesses: 30 },
  { name: "Chaman", slug: "chaman", businesses: 60 },
  { name: "Tando Adam", slug: "tando-adam", businesses: 90 },
  { name: "Tando Allahyar", slug: "tando-allahyar", businesses: 80 },
  { name: "Usta Muhammad", slug: "usta-muhammad", businesses: 30 },
]

export const categories = [
  { name: "Restaurants", slug: "restaurants", count: 1250, icon: "🍽️" },
  { name: "Healthcare", slug: "healthcare", count: 890, icon: "🏥" },
  { name: "Education", slug: "education", count: 650, icon: "🎓" },
  { name: "Automotive", slug: "automotive", count: 420, icon: "🚗" },
  { name: "Retail", slug: "retail", count: 980, icon: "🛍️" },
  { name: "Beauty & Spa", slug: "beauty-spa", count: 340, icon: "💄" },
  { name: "Real Estate", slug: "real-estate", count: 560, icon: "🏠" },
  { name: "Technology", slug: "technology", count: 290, icon: "💻" },
  { name: "Legal Services", slug: "legal", count: 180, icon: "⚖️" },
  { name: "Construction", slug: "construction", count: 320, icon: "🏗️" },
  { name: "Travel & Tourism", slug: "travel", count: 210, icon: "✈️" },
  { name: "Financial Services", slug: "finance", count: 150, icon: "💰" },
]
