export const mockBusinesses = [
  {
    id: "1",
    name: "Al-Madina Restaurant",
    category: "Restaurants",
    city: "karachi",
    address: "Block 15, Gulshan-e-Iqbal, Karachi",
    phone: "+92-21-34567890",
    whatsapp: "+92-300-1234567",
    email: "info@almadinarest.com",
    description: "Authentic Pakistani cuisine with traditional flavors. Family-friendly dining experience.",
    image: "/pakistani-restaurant-interior.png",
  },
  {
    id: "2",
    name: "City Hospital",
    category: "Healthcare",
    city: "lahore",
    address: "Main Boulevard, Gulberg III, Lahore",
    phone: "+92-42-35678901",
    email: "contact@cityhospital.pk",
    description: "Modern healthcare facility with experienced doctors and advanced medical equipment.",
    image: "/modern-hospital.png",
  },
  {
    id: "3",
    name: "Tech Solutions Hub",
    category: "Technology",
    city: "islamabad",
    address: "Blue Area, F-6, Islamabad",
    phone: "+92-51-23456789",
    email: "hello@techsolutions.pk",
    description: "Leading IT services company providing software development and digital solutions.",
    image: "/modern-tech-office.png",
  },
  {
    id: "4",
    name: "Green Valley School",
    category: "Education",
    city: "rawalpindi",
    address: "Satellite Town, Rawalpindi",
    phone: "+92-51-34567890",
    email: "admissions@greenvalley.edu.pk",
    description: "Quality education from nursery to matriculation with modern teaching methods.",
    image: "/school-building-with-playground.png",
  },
  {
    id: "5",
    name: "Auto Care Center",
    category: "Automotive",
    city: "faisalabad",
    address: "Sargodha Road, Faisalabad",
    phone: "+92-41-23456789",
    whatsapp: "+92-300-9876543",
    email: "service@autocare.pk",
    description: "Complete automotive services including repairs, maintenance, and spare parts.",
    image: "/car-repair-garage.png",
  },
  {
    id: "6",
    name: "Fashion Plaza",
    category: "Retail",
    city: "karachi",
    address: "Tariq Road, Karachi",
    phone: "+92-21-45678901",
    email: "info@fashionplaza.pk",
    description: "Latest fashion trends and clothing for men, women, and children.",
    image: "/clothing-store-interior.png",
  },
  {
    id: "7",
    name: "Beauty Lounge",
    category: "Beauty & Spa",
    city: "lahore",
    address: "MM Alam Road, Gulberg, Lahore",
    phone: "+92-42-45678901",
    whatsapp: "+92-300-5555555",
    email: "bookings@beautylounge.pk",
    description: "Premium beauty services including hair styling, skincare, and spa treatments.",
    image: "/modern-beauty-salon.png",
  },
  {
    id: "8",
    name: "Prime Properties",
    category: "Real Estate",
    city: "islamabad",
    address: "Jinnah Avenue, Blue Area, Islamabad",
    phone: "+92-51-56789012",
    email: "sales@primeproperties.pk",
    description: "Trusted real estate agency for buying, selling, and renting properties.",
    image: "/real-estate-office.png",
  },
  {
    id: "9",
    name: "Legal Associates",
    category: "Legal Services",
    city: "karachi",
    address: "I.I. Chundrigar Road, Karachi",
    phone: "+92-21-67890123",
    email: "contact@legalassociates.pk",
    description: "Professional legal services for corporate and individual clients.",
    image: "/law-office-interior.png",
  },
  {
    id: "10",
    name: "Build Right Construction",
    category: "Construction",
    city: "rawalpindi",
    address: "Committee Chowk, Rawalpindi",
    phone: "+92-51-78901234",
    whatsapp: "+92-300-7777777",
    email: "projects@buildright.pk",
    description: "Quality construction services for residential and commercial projects.",
    image: "/construction-company-office.png",
  },
  {
    id: "11",
    name: "Travel World",
    category: "Travel & Tourism",
    city: "lahore",
    address: "Liberty Market, Gulberg, Lahore",
    phone: "+92-42-78901234",
    email: "bookings@travelworld.pk",
    description: "Complete travel solutions including domestic and international tour packages.",
    image: "/travel-agency-office.png",
  },
  {
    id: "12",
    name: "Financial Advisors",
    category: "Financial Services",
    city: "islamabad",
    address: "Kohsar Market, F-6, Islamabad",
    phone: "+92-51-89012345",
    email: "info@financialadvisors.pk",
    description: "Expert financial planning and investment advisory services.",
    image: "/financial-advisor-office.png",
  },
]

export const cities = [
  { name: "Karachi", slug: "karachi", businesses: 3200 },
  { name: "Lahore", slug: "lahore", businesses: 2800 },
  { name: "Islamabad", slug: "islamabad", businesses: 1900 },
  { name: "Rawalpindi", slug: "rawalpindi", businesses: 1200 },
  { name: "Faisalabad", slug: "faisalabad", businesses: 980 },
  { name: "Multan", slug: "multan", businesses: 750 },
  { name: "Peshawar", slug: "peshawar", businesses: 650 },
  { name: "Quetta", slug: "quetta", businesses: 420 },
  { name: "Sialkot", slug: "sialkot", businesses: 380 },
  { name: "Gujranwala", slug: "gujranwala", businesses: 320 },
]

export const categories = [
  { name: "Restaurants", slug: "restaurants", count: 1250, icon: "🍽️" },
  { name: "Healthcare", slug: "healthcare", count: 890, icon: "🏥" },
  { name: "Education", slug: "education", count: 650, icon: "🎓" },
  { name: "Automotive", slug: "automotive", count: 420, icon: "🚗" },
  { name: "Retail", slug: "retail", count: 980, icon: "🛍️" },
  { name: "Beauty & Spa", slug: "beauty-spa", count: 340, icon: "💄" },
  { name: "Real Estate", slug: "real-estate", count: 560, icon: "🏠" },
  { name: "Technology", slug: "technology", count: 290, icon: "💻" },
  { name: "Legal Services", slug: "legal", count: 180, icon: "⚖️" },
  { name: "Construction", slug: "construction", count: 320, icon: "🏗️" },
  { name: "Travel & Tourism", slug: "travel", count: 210, icon: "✈️" },
  { name: "Financial Services", slug: "finance", count: 150, icon: "💰" },
]
